### ISSUE TITLE
`bundle.js` not found or 404

### ISSUE THREAD

**Issue by locmai0808** [Damhan/Serify#1]
https://github.com/Damhan/Serify/blob/3f1f89b8517aebaed7c0520136ea721e2f202189/public/index.html#L32 

It's manually added, and your homepage is https://damhan.github.io/Serify/. So you may want to change it to:

```HTML
<script src="/Serify/bundle.js">
```

**Comment by Damhan** [comment]
This resolves the issue, thank you.
